import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// Docs scaffold for Taro. Branding/tooling is set up; the docs *content
// structure* (sidebar, pages) is intentionally left minimal — add files under
// docs/ and the autogenerated sidebar will pick them up.
const config: Config = {
  title: 'Taro',
  tagline: 'A curve-native, self-hosted experiment tracker',
  favicon: 'img/favicon.ico',

  // TODO: set to the real docs URL when you deploy (e.g. GitHub Pages).
  url: 'https://steliosgrs.github.io',
  baseUrl: '/taro/',

  organizationName: 'steliosgrs',
  projectName: 'taro',

  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          editUrl: 'https://github.com/steliosgrs/taro/tree/main/website/',
        },
        // No blog for now — flip to a config object to enable it.
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    image: 'img/docusaurus-social-card.jpg',
    navbar: {
      title: 'Taro',
      logo: {
        alt: 'Taro',
        src: 'img/logo.svg',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'docsSidebar',
          position: 'left',
          label: 'Docs',
        },
        {
          href: 'https://github.com/steliosgrs/taro',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            {
              label: 'Introduction',
              to: '/docs/intro',
            },
          ],
        },
        {
          title: 'More',
          items: [
            {
              label: 'GitHub',
              href: 'https://github.com/steliosgrs/taro',
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Taro. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
