import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The sidebar is autogenerated from the docs/ folder structure, so you can shape
 * the docs yourself: add files and subfolders under docs/ and they appear here.
 * Use `_category_.json` in a subfolder to label/order a category, or replace the
 * autogenerated entry below with an explicit list when you want full control.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
